# not a route - this imports another file
#this_does_not_matter:
#    resource: routes_api.yaml

#app_lucky_number:
#    path: /lucky/number/{max<\d+>}
#    controller: App\Controller\LuckyController::number
#    defaults:
#        max: 100

api_lucky_number:
    path: /api/lucky/number/{max<\d+>}
    controller: App\Controller\LuckyController::numberApi
    defaults:
        max: 100

app_foo:
    path: /foo
    controller: App\Controller\FooController

#    requirements:
#        max: '\d+'

#
#app_blog_list:
#    path: /blog/{page<\d+>}
#
#app_blog_about:
#    path: /blog/about
#
#app_blog_show:
#    path: /blog/{slug}
